

# Executive Summary {.front-matter .unnumbered} 

Nupqu Resource Limited Partnership was retained by the Canadian Wildlife Federation in the summer of 2021 to conduct fish passage and habitat confirmation assessments at road-stream crossings and dams within the Elk River watershed group as part of connectivity restoration planning targeting westslope cutthrout trout. New Graph Environment Ltd. was sub-contracted by Nupqu to assist with project delivery. The assessments conducted in 2021 complement work completed in 2020 which can be viewed interactively online at https://newgraphenvironment.github.io/fish_passage_elk_2020_reporting_cwf/ [@irvine2021UpperElk].
`r if(identical(gitbook_on, FALSE))knitr::asis_output("This report is available as pdf and as an online interactive report at https://newgraphenvironment.github.io/fish_passage_elk_2021_reporting/. Viewing online is recommended as the web-hosted version contains more features and is more easily navigable.")` 


<br>


The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing habitat [@Bramblett_2002; @swalesRoleOffChannelPonds1989; @diebel_etal2015EffectsRoad].  Culverts can present barriers to fish migration due to low water depth, increased water velocity, turbulence, a vertical drop at the culvert outlet and/or maintenance issues [@slaneyFishHabitatRehabilitation1997; @cote_etal2005Fishpassage].  Also of relevance to aquatic connectivity, there are a multitude of dam structures historically installed throughout the province for numerous purposes such as water extraction and hydropower generation. 


<br>


In 2021, fish passage assessments were conducted at `r pscis_phase1 %>% nrow()` stream crossing sites with `r pscis_phase1 %>% filter(barrier_result == 'Passable') %>% nrow()` crossings considered "passable", `r pscis_phase1 %>% filter(barrier_result == 'Potential') %>% nrow() %>% english::as.english()` crossing considered "potential" barriers and `r pscis_phase1 %>% filter(barrier_result == 'Barrier') %>% nrow() ` crossing considered "barriers" according to threshold values based on culvert embedment, outlet drop, slope, diameter (relative to channel size) and length [@fish_passage_assessments].  Additionally, although all were considered fully passable, `r pscis_phase1 %>% filter(barrier_result == 'Unknown') %>% nrow() %>% english::as.english()` crossings assessed were fords and thus assigned "unknown" status according to the provincial protocol. In addition, three historic dam locations were assessed for fish passage including sites on `r tab_dams_raw %>% arrange(id) %>% pull(stream) %>% knitr::combine_words()`.

<br>

In 2021, habitat confirmation assessments were conducted at `r hab_site_priorities %>% nrow()` sites in the Elk River watershed group with a total of approximately `r habitat_confirmations_priorities %>% pull(survey_length_m) %>% sum() %>% round(-3)/1000`km of stream surveyed. As these assessments are intended to supplement data and insights from numerous other programs underway in the region and because collaborative decision making was ongoing at the time of reporting, site prioritization can be considered preliminary and a starting point for discussions with connectivity partners, stakeholders and industry/regulatory professionals.  `r hab_site_priorities %>% filter(priority %ilike% 'high') %>% nrow() %>% english::as.english() %>% str_to_title()` crossings were rated as high priorities for proceeding to design for replacement, `r hab_site_priorities %>% filter(priority %ilike% 'Moderate') %>% nrow() %>% english::as.english()` crossings were rated as moderate priorities, and `r hab_site_priorities %>% filter(priority %ilike% 'Low') %>% nrow() %>% english::as.english()` crossings were rated as low priorities.  Only summary tables and raw data are provided for surveys conducted within the Flathead River sub-basin with additional reporting potentially provided for these sites in the future under separate cover. Detailed information for each site assessed with Phase 2 assessments on streams that drain into the Elk River are presented within site specific appendices to this document.  In addition, fish passage assessments of dams located on `r tab_dams_raw %>% arrange(id) %>% pull(stream) %>% knitr::combine_words()` were conducted with results presented within the "Results and Discussion" section. 

<br>

Effective connectivity restoration planning incorporates a watershed based approach and develops an understanding of subject aquatic systems to a level where actions prioritized are highly likely to address limiting factors and increase the productivity of local fish populations. Leveraging of research initiatives in the region as well as baseline and follow up monitoring is important to foster this understanding in the Elk River watershed group where there are opportunities to restore connectivity by ensuring that fish passage considerations are incorporated into repair, replacement, relocation and deactivation designs for both stream crossing barrier and dam barrier structures.

